#!/usr/bin/python3

import sys

numbers = []

for line in sys.stdin:
    line = float(line)
    numbers.append(line)

mean = sum(numbers) / len(numbers)
variance = sum((x - mean) ** 2 for x in numbers) / len(numbers)

print(variance)

